/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "criptografia.h"


int
main (int argc, char *argv[])
{
	 CLIENT *clnt;
	 char *result;
	 char *server;
	 operands param_env;

	 server = argv[1];
	 strcpy(param_env.palavra,argv[2]);
	 param_env.salto = atoi(argv[3]);
	 
	 /* Cria "handle" cliente usado para chamar MESSAGEPROG no servidor designado na linha de comando. */
	 
	 clnt = clnt_create(server, CRIPT_PROG, CRIPT_VERSION, "udp");
	 
if (clnt == (CLIENT *)NULL) {
	 /* Nao pode estabilizar conexao com o servidor. */
	 printf (" Erro clnt_create" );
	 clnt_pcreateerror(server);
	 fflush (stdout);
	 exit(1);
	 }

	 /* Chamada ao metodo enviar_1 no servidor */
	 result = *(enviar_1 (&param_env, clnt));

	 if (result == (char *)NULL) {
	 /* Algum erro ocorreu ao se comunicar com o servidor. */
	 printf("Algum erro ocorreu ao se comunicar com o servidor");
	 clnt_perror(clnt, server);
	 exit(1);
	 }

	if (*result == 0) {
	 /* Server nao e capaz de imprimir sua mensagem. */
	 printf(stderr, "%s: Server nao e capaz de imprimir sua mensagem\n",argv[0]);
	 exit(1);
	 }

 	 
	 /* Imprimir mensagens no console */
	 printf("Mensagem enviada: %s\n",param_env.palavra);
	 printf("Mensagem criptada: %s\n\n", result);
	 
	 clnt_destroy( clnt );
	 exit(0);
}
