/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "criptografia.h"

bool_t
xdr_operands (XDR *xdrs, operands *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->palavra, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->salto))
		 return FALSE;
	return TRUE;
}
