/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CRIPTOGRAFIA_H_RPCGEN
#define _CRIPTOGRAFIA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	char palavra[20];
	int salto;
};
typedef struct operands operands;

#define CRIPT_PROG 12345678
#define CRIPT_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define ENVIAR 1
extern  char ** enviar_1(operands *, CLIENT *);
extern  char ** enviar_1_svc(operands *, struct svc_req *);
extern int cript_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ENVIAR 1
extern  char ** enviar_1();
extern  char ** enviar_1_svc();
extern int cript_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CRIPTOGRAFIA_H_RPCGEN */
